eureka:
  client:
    service-url:
       defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
---
spring:
  profiles: subject
words: Yo,Tu,El,Ella,Esto

---
spring:
  profiles: verb
words: corrió, sabía, tenía, vió, compró

---
spring:
  profiles: article
words: un,una,la

---
spring:
  profiles: adjective
words: razonable, permeable, sospechoso, ordinario, improbable

---
spring:
  profiles: noun
words: barco, libro, voto, asiento, mochila, partición

---
spring:
  profiles: primary
server:
  port: 8011

---
spring:
  profiles: secondary
server:
  port: 8012
  
---
spring:
  profiles: tertiary
server:
  port: 8013
